- type: gameMapPool
  id: CorvaxDefaultMapPool
  maps:
  # Мапперская авантюра
  ## Highpop
  #- CorvaxDelta
  #- CorvaxAvrite
  #- CorvaxAstra
  #- CorvaxPilgrim
  #- CorvaxGlacier
  #- Box
  ## Midpop
  #- CorvaxPaper
  ##- CorvaxPearl — До реворка
  #- CorvaxOutpost
  #- CorvaxAwesome
  #- Bagel
  #- Marathon
  ##- Train — До реворка оффами
  ## Lowpop
  #- CorvaxSilly
  #- CorvaxMaus
  #- CorvaxTushkan
  #- Packed
  #- Omega
  #================
  # Highpop
  - Box
  - Bagel
  - Cog
  - Fland
  - Origin
  # Midpop
  - Amber
  - Marathon
  - Meta
  # Lowpop
  - Saltern
  - Omega
  - Packed
